// Code generated by "stringer -type=MapItfErrorCode"; DO NOT EDIT.

package itferr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownErr - -1]
	_ = x[InitParseFailed-1001]
	_ = x[InitParamTypeErr-2001]
	_ = x[ExceptObject-2002]
	_ = x[KeyTypeErr-3001]
	_ = x[ValueTypeErr-3002]
	_ = x[ValueConvertFailed-3003]
	_ = x[BaseTypeConvertFailed-3004]
	_ = x[KeyNotFound-3005]
	_ = x[GetFuncTypeInconsistent-3006]
	_ = x[IllegalMapObject-3007]
	_ = x[EmptyMapObject-3008]
	_ = x[ListIndexIllegal-4001]
	_ = x[UnSupportInterfaceFunc-5001]
	_ = x[CurrentCannotUseIndex-5002]
	_ = x[TypeMismatchErr-5003]
	_ = x[FuncUsedErr-5004]
	_ = x[UnrecoverablePanicErr-5005]
	_ = x[SetValueErr-6001]
	_ = x[UnSupportSetValTypeErr-6002]
	_ = x[IterChainIsEmpty-6003]
	_ = x[IterChainPreElementIsNil-6004]
}

const (
	_MapItfErrorCode_name_0 = "UnknownErr"
	_MapItfErrorCode_name_1 = "InitParseFailed"
	_MapItfErrorCode_name_2 = "InitParamTypeErrExceptObject"
	_MapItfErrorCode_name_3 = "KeyTypeErrValueTypeErrValueConvertFailedBaseTypeConvertFailedKeyNotFoundGetFuncTypeInconsistentIllegalMapObjectEmptyMapObject"
	_MapItfErrorCode_name_4 = "ListIndexIllegal"
	_MapItfErrorCode_name_5 = "UnSupportInterfaceFuncCurrentCannotUseIndexTypeMismatchErrFuncUsedErrUnrecoverablePanicErr"
	_MapItfErrorCode_name_6 = "SetValueErrUnSupportSetValTypeErrIterChainIsEmptyIterChainPreElementIsNil"
)

var (
	_MapItfErrorCode_index_2 = [...]uint8{0, 16, 28}
	_MapItfErrorCode_index_3 = [...]uint8{0, 10, 22, 40, 61, 72, 95, 111, 125}
	_MapItfErrorCode_index_5 = [...]uint8{0, 22, 43, 58, 69, 90}
	_MapItfErrorCode_index_6 = [...]uint8{0, 11, 33, 49, 73}
)

func (i MapItfErrorCode) String() string {
	switch {
	case i == -1:
		return _MapItfErrorCode_name_0
	case i == 1001:
		return _MapItfErrorCode_name_1
	case 2001 <= i && i <= 2002:
		i -= 2001
		return _MapItfErrorCode_name_2[_MapItfErrorCode_index_2[i]:_MapItfErrorCode_index_2[i+1]]
	case 3001 <= i && i <= 3008:
		i -= 3001
		return _MapItfErrorCode_name_3[_MapItfErrorCode_index_3[i]:_MapItfErrorCode_index_3[i+1]]
	case i == 4001:
		return _MapItfErrorCode_name_4
	case 5001 <= i && i <= 5005:
		i -= 5001
		return _MapItfErrorCode_name_5[_MapItfErrorCode_index_5[i]:_MapItfErrorCode_index_5[i+1]]
	case 6001 <= i && i <= 6004:
		i -= 6001
		return _MapItfErrorCode_name_6[_MapItfErrorCode_index_6[i]:_MapItfErrorCode_index_6[i+1]]
	default:
		return "MapItfErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
